apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bootstrap-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Elektro private cluster root
  secretName: platform-root-ca
  duration: 87600h
  renewBefore: 8760h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    name: bootstrap-selfsigned
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: platform-ca
spec:
  ca:
    secretName: platform-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edge-tls
  namespace: edge
spec:
  secretName: edge-tls
  dnsNames:
  - '*.internal'
  - '*.admin.internal'
  - '*.test.internal'
  - '*.staging.internal'
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    name: platform-ca
