apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public
  namespace: edge
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
      envoyService:
        annotations:
          lbipam.cilium.io/ips: ${PUBLIC_EDGE_IP}
        externalTrafficPolicy: Cluster
        allocateLoadBalancerNodePorts: false
  filterOrder:
  - name: envoy.filters.http.oauth2
    before: envoy.filters.http.jwt_authn
  - name: envoy.filters.http.ext_authz
    after: envoy.filters.http.jwt_authn
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: public
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: public
    namespace: edge
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: edge
spec:
  gatewayClassName: public
  listeners:
  - name: identity
    hostname: ${IDENTITY_HOST}
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: public-edge-tls
    allowedRoutes:
      namespaces:
        from: Same
  - name: apps
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: public-edge-tls
    allowedRoutes:
      namespaces:
        from: Same
