apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cnpg-storage-default
spec:
  background: false
  webhookConfiguration:
    failurePolicy: Fail
    timeoutSeconds: 10
  rules:
  - name: data-storage
    match:
      any:
      - resources:
          kinds:
          - postgresql.cnpg.io/v1/Cluster
          operations:
          - CREATE
          - UPDATE
    preconditions:
      all:
      - key: '{{ request.object.spec.storage.storageClass || '''' }}'
        operator: Equals
        value: ''
    mutate:
      patchStrategicMerge:
        spec:
          storage:
            storageClass: longhorn-cnpg
  - name: wal-storage
    match:
      any:
      - resources:
          kinds:
          - postgresql.cnpg.io/v1/Cluster
          operations:
          - CREATE
          - UPDATE
    preconditions:
      all:
      - key: '{{ contains(keys(request.object.spec), ''walStorage'') }}'
        operator: Equals
        value: true
      - key: '{{ request.object.spec.walStorage.storageClass || '''' }}'
        operator: Equals
        value: ''
    mutate:
      patchStrategicMerge:
        spec:
          walStorage:
            storageClass: longhorn-cnpg
