apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: cnpg-storage-default
spec:
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  webhookConfiguration:
    timeoutSeconds: 10
  evaluation:
    admission:
      enabled: true
    background:
      enabled: false
    mutateExisting:
      enabled: false
  matchConstraints:
    resourceRules:
    - apiGroups:
      - postgresql.cnpg.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - clusters
  mutations:
  - patchType: JSONPatch
    jsonPatch:
      expression: >-
        has(object.spec.storage) &&
        (!has(object.spec.storage.storageClass) || object.spec.storage.storageClass == '')
        ? [JSONPatch{op: 'add', path: '/spec/storage/storageClass', value: 'longhorn-cnpg'}]
        : []
  - patchType: JSONPatch
    jsonPatch:
      expression: >-
        has(object.spec.walStorage) &&
        (!has(object.spec.walStorage.storageClass) || object.spec.walStorage.storageClass == '')
        ? [JSONPatch{op: 'add', path: '/spec/walStorage/storageClass', value: 'longhorn-cnpg'}]
        : []
