apiVersion: v1
kind: Namespace
metadata:
  name: app-demo
  labels:
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      automountServiceAccountToken: false
      containers:
      - name: demo
        image: registry.k8s.io/e2e-test-images/agnhost:2.53
        args:
        - netexec
        - --http-port=8080
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /hostname
            port: http
      nodeSelector:
        elektro.local/workloads: 'true'
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: app-demo
spec:
  selector:
    app: demo
  ports:
  - name: http
    port: 8080
    targetPort: http
