apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-db
  namespace: app-demo
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  enableSuperuserAccess: false
  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-standard-trixie
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: app
      owner: app
  affinity:
    nodeSelector:
      elektro.local/workloads: 'true'
    enablePodAntiAffinity: true
    podAntiAffinityType: required
