apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundation
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/foundation
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/cilium
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: foundation
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/controllers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admission
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/admission
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/storage
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: admission
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/network
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: admission
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/certificates
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./clusters/laptops/secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: foundation
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/databases
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: storage
  - name: secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: identity
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/identity
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: databases
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authorization
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/authorization
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: databases
  - name: authorino-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: edge
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/edge
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: network
  - name: certificates
  - name: identity
  - name: authorization
  - name: admission
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: access
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/access
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: edge
  healthCheckExprs:
  - apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    current: has(status) && has(status.ancestors) && status.ancestors.size() >= 4 && status.ancestors.all(a, a.conditions.exists(c,
      c.type == 'Accepted' && c.status == 'True' && c.observedGeneration == metadata.generation))
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routes
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 20m
  path: ./infrastructure/routes
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: access
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authorino-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./install/crd
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: authorino-upstream
  dependsOn:
  - name: foundation
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/dns
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: network
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-dns
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  path: ./infrastructure/cluster-dns
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
  dependsOn:
  - name: dns
