apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  BASE_DOMAIN: example.com
  API_HOST: 192.168.50.11
  POD_CIDR: 10.42.0.0/16
  LB_START: 192.168.50.240
  LB_STOP: 192.168.50.249
  EDGE_IP: 192.168.50.240
  LAN_INTERFACE_REGEX: ^en.*
  FGA_STORE_ID: NOT_CONFIGURED
  FGA_MODEL_ID: NOT_CONFIGURED
  PG_IMAGE: ghcr.io/cloudnative-pg/postgresql:17.11-standard-trixie
