#!/usr/bin/env bash
# Sent over SSH by the maintenance CLIs. All mutations run on the verified target host.
set -euo pipefail
operation=${1:?} node=${2:?} expected_machine=${3:?} node_uid=${4:?} role=${5:?} version=${6:?}
die() { echo "Host check failed: $*" >&2; exit 1; }
[[ $EUID == 0 ]] || die 'root access is required.'
for value in "$node" "$expected_machine" "$node_uid" "$role" "$version"; do
  [[ $value =~ ^[A-Za-z0-9._+-]+$ ]] || die 'invalid argument.'
done
[[ $(cat /etc/machine-id) == "$expected_machine" ]] || die 'SSH machine does not match the Kubernetes Node machineID.'
cfg=/etc/rancher/k3s/config.yaml
backup=/var/backups/elektro-k3s/$node/$node_uid
unit=k3s
[[ $role != worker ]] || unit=k3s-agent
umask 077

check_config() {
  [[ ${K3S_DATA_DIR:-/var/lib/rancher/k3s} == /var/lib/rancher/k3s ]] || die 'custom K3S_DATA_DIR environment is unsupported.'
  [[ -z ${K3S_CONFIG_FILE:-} ]] || die 'custom K3S_CONFIG_FILE environment is unsupported.'
  [[ -f $cfg && ! -L $cfg ]] || die 'expected the regular config.yaml generated by install-k3s.sh.'
  [[ $(awk -F '"' '/^node-name: / {print $2}' "$cfg") == "$node" ]] || die 'configured node-name differs.'
  [[ $(/usr/local/bin/k3s --version | awk 'NR == 1 {print $3}') == "$version" ]] || die 'installed version differs from the repository pin.'
  # These helpers deliberately support the repository default paths/configuration, not arbitrary k3s installs.
  if grep -Eq '^(data-dir|datastore-endpoint|disable-etcd|disable-apiserver|disable-agent):' "$cfg"; then
    die 'custom datastore, paths or split server modes need their own migration procedure.'
  fi
  if [[ -d /etc/rancher/k3s/config.yaml.d ]] && find /etc/rancher/k3s/config.yaml.d -type f -name '*.yaml' -print -quit | grep -q .; then
    die 'merge/review config.yaml.d overrides before using these helpers.'
  fi
  local unit_config
  unit_config=$(systemctl cat "$unit")
  if grep -Eq -- '(--(data-dir|config|node-label|node-taint|disable-etcd|datastore-endpoint)(=|[[:space:]])|K3S_(DATA_DIR|CONFIG_FILE|NODE_LABEL|NODE_TAINT|DATASTORE_ENDPOINT)=)' <<<"$unit_config"; then
    die 'systemd overrides conflict with the repository-managed configuration.'
  fi
  local env_file
  for env_file in "/etc/systemd/system/$unit.service.env" "/etc/default/$unit" "/etc/sysconfig/$unit"; do
    if [[ -f $env_file ]] && grep -Eq '(^|[[:space:]])K3S_(DATA_DIR|CONFIG_FILE|NODE_LABEL|NODE_TAINT|DATASTORE_ENDPOINT)=' "$env_file"; then
      die 'service environment overrides require manual review.'
    fi
  done
}

case $operation in
  inspect)
    check_config
    for cmd in ip iptables-save iptables-restore ip6tables-save ip6tables-restore pgrep pkill; do
      command -v "$cmd" >/dev/null || die "required host command $cmd is missing."
    done
    other_unit=k3s-agent
    [[ $unit != k3s-agent ]] || other_unit=k3s
    ! systemctl is-active --quiet "$other_unit" || die 'both agent and server services are running.'
    if [[ $role == worker ]]; then
      [[ ! -d /var/lib/rancher/k3s/server/db/etcd ]] || die 'worker still has server datastore state.'
    else
      [[ -d /var/lib/rancher/k3s/server/db/etcd ]] || die 'server has no embedded etcd datastore.'
    fi
    systemctl is-active --quiet "$unit" || die "$unit is not active."
    [[ -x /usr/local/bin/$unit-uninstall.sh ]] || die 'upstream uninstall script is missing.'
    echo "Verified $node over SSH: $role, $version."
    ;;
  backup)
    check_config
    install -d -m 0700 "$backup"
    if [[ ! -e $backup/config ]]; then cp -a /etc/rancher/k3s "$backup/config"; fi
    if [[ ! -e $backup/node-password && -f /etc/rancher/node/password ]]; then cp -a /etc/rancher/node/password "$backup/node-password"; fi
    if [[ $role != worker && ! -e $backup/snapshot-complete ]]; then
      cp -a /var/lib/rancher/k3s/server/token "$backup/server-token"
      # Outside k3s's data directory so the upstream uninstaller cannot remove the new snapshot.
      /usr/local/bin/k3s etcd-snapshot save --name elektro-before-maintenance --etcd-snapshot-dir "$backup/etcd" \
        >"$backup/snapshot.log" 2>&1 || die "snapshot failed; inspect $backup/snapshot.log."
      touch "$backup/snapshot-complete"
    fi
    echo "Root-only host backup: $backup (copy it off this machine for disaster recovery)."
    ;;
  stop)
    [[ -d $backup/config ]] || die 'maintenance backup is missing.'
    systemctl disable --now "$unit"
    ! systemctl is-active --quiet "$unit" || die 'k3s did not stop.'
    ;;
  stopped)
    ! systemctl is-active --quiet k3s || die 'server service is still running.'
    ! systemctl is-active --quiet k3s-agent || die 'agent service is still running.'
    ;;
  uninstall)
    [[ -d $backup/config ]] || die 'maintenance backup is missing.'
    ! systemctl is-active --quiet k3s || die 'stop the server before uninstalling.'
    ! systemctl is-active --quiet k3s-agent || die 'stop the agent before uninstalling.'
    if [[ -e $backup/uninstall-complete ]]; then echo 'Host was already uninstalled; reboot before joining.'; exit 0; fi
    [[ -x /usr/local/bin/$unit-uninstall.sh ]] || die 'upstream uninstaller is missing; inspect the host before resuming.'
    # Stop Cilium's agent before removing interfaces so it cannot recreate them during cleanup.
    if cilium_ids=$(/usr/local/bin/k3s crictl --timeout=10s ps --name cilium-agent -q 2>/dev/null); then
      while read -r container_id; do
        [[ -z $container_id ]] || /usr/local/bin/k3s crictl --timeout=30s stop "$container_id" >/dev/null
      done <<<"$cilium_ids"
    fi
    # containerd may already have exited with k3s, leaving container processes alive.
    # The stopped kubelet cannot restart them. Terminate only Cilium's exact process name.
    if pgrep -x cilium-agent >/dev/null; then pkill -TERM -x cilium-agent; fi
    for attempt in {1..30}; do
      if ! pgrep -x cilium-agent >/dev/null; then break; fi
      [[ $attempt != 30 ]] || die 'Cilium agent did not stop; networking was not removed.'
      sleep 1
    done
    for dev in cilium_host cilium_net cilium_vxlan cilium_wg0; do
      if ip link show dev "$dev" >/dev/null 2>&1; then ip link delete "$dev"; fi
    done
    # Follow k3s's Cilium-specific cleanup; preserve unrelated host firewall rules.
    iptables-save >"$backup/iptables-before-cleanup"
    ip6tables-save >"$backup/ip6tables-before-cleanup"
    awk 'tolower($0) !~ /cilium/' "$backup/iptables-before-cleanup" | iptables-restore
    awk 'tolower($0) !~ /cilium/' "$backup/ip6tables-before-cleanup" | ip6tables-restore
    install -d -m 0700 /var/lib/elektro-k3s
    cat /proc/sys/kernel/random/boot_id >/var/lib/elektro-k3s/rejoin-requires-reboot
    /usr/local/bin/"$unit"-uninstall.sh >"$backup/uninstall.log" 2>&1 \
      || die "upstream uninstall failed; inspect $backup/uninstall.log."
    touch "$backup/uninstall-complete"
    echo 'Upstream k3s uninstall completed. /var/lib/longhorn was not deleted. Reboot before joining.'
    ;;
  controller|hybrid)
    [[ $role != worker ]] || die 'worker/server conversions must remove and rejoin.'
    check_config
    [[ -d $backup/config ]] || die 'maintenance backup is missing.'
    # Only edit this repository's three role labels; preserve unrelated settings and taints.
    for key in elektro.local/role elektro.local/workloads node.longhorn.io/create-default-disk; do
      [[ $(grep -Fc "  - \"$key=" "$cfg") == 1 ]] || die "expected one generated $key label."
    done
    tmp=$(mktemp /etc/rancher/k3s/.elektro-role.XXXXXX)
    trap 'rm -f -- "$tmp"' EXIT
    awk -v role="$operation" '
      function taints_done() {
        if (!in_taints) return
        if (role == "controller") taints=taints "  - \"elektro.local/dedicated=control-plane:NoSchedule\"\n"
        if (taints != "") printf "node-taint:\n%s", taints
        in_taints=0; taints=""; saw_taints=1
      }
      /^node-taint:/ {
        if ($0 != "node-taint:") exit 2
        in_taints=1; next
      }
      in_taints && /^[^[:space:]#]/ { taints_done() }
      in_taints {
        if ($0 !~ /elektro[.]local\/dedicated=/) taints=taints $0 "\n"
        next
      }
      /"elektro.local\/role=/ { $0="  - \"elektro.local/role=" role "\"" }
      /"elektro.local\/workloads=/ { $0="  - \"elektro.local/workloads=" (role == "controller" ? "false" : "true") "\"" }
      /"node.longhorn.io\/create-default-disk=/ { $0="  - \"node.longhorn.io/create-default-disk=" (role == "controller" ? "false" : "true") "\"" }
      { print }
      END {
        taints_done()
        if (!saw_taints && role == "controller") print "node-taint:\n  - \"elektro.local/dedicated=control-plane:NoSchedule\""
      }
    ' "$cfg" >"$tmp" || die 'unsupported node-taint formatting; original config was not changed.'
    chmod --reference="$cfg" "$tmp"
    chown --reference="$cfg" "$tmp"
    mv -- "$tmp" "$cfg"
    echo "Persisted server role $operation; the running server is not restarted."
    ;;
  *) die 'unknown operation.' ;;
esac
