apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- resources.yaml
- network.yaml
configMapGenerator:
- name: lan-dns
  files:
  - Corefile
  - internal.db
  - empty.db
generatorOptions:
  # CoreDNS reloads both configuration and zone files without restarting pods.
  disableNameSuffixHash: true
